[package]
name = "aoc"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "aoc"
path = "day18.rs"

[dependencies]
regex = "1.5"
lazy_static = "1.4"
bigdecimal = "0.2"
pancurses = "0.16"

[profile.release]
# Executable size experiments
#opt-level = 'z'
#lto = true
#panic = 'abort'
