[package]
name = "aoc"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "aoc"
path = "16.rs"

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
bigdecimal = "0.2.0"

[profile.release]
# Executable size experiments
#opt-level = 'z'
#lto = true
#panic = 'abort'
