[package]
name = "pouet"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "aoc"
path = "04.rs"

[dependencies]
regex = "1.4.2"

[profile.release]
# Executable size experiments
opt-level = 'z'
lto = true
panic = 'abort'